services:
  uvm-debug-agent:
    build: .
    container_name: uvm-debug-agent
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./reports:/app/reports
      - ./configs:/app/configs
    environment:
      - EMBEDDING_API_KEY=${EMBEDDING_API_KEY}
      - EMBEDDING_API_BASE_URL=${EMBEDDING_API_BASE_URL}
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_API_BASE_URL=${LLM_API_BASE_URL}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3 