default_embedding_model: text-embedding-3-small
default_model: gpt-4o-mini
default_rag_mode: unified_adaptive
embedding_dimension: 1536
enable_unified_rag: true
unified_rag_default: true
vector_store_path: ./data/vectorstore/unified_openai_1536d
